# Generated by Django 5.0.6 on 2024-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=15)),
                ('manual_input', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('csv_file', models.FileField(upload_to='csv_files/')),
                ('additional_file', models.FileField(upload_to='additional_files/')),
                ('schedule_from', models.IntegerField()),
                ('schedule_to', models.IntegerField()),
                ('days', models.JSONField()),
                ('weeks', models.IntegerField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('phone_numbers', models.JSONField()),
                ('schedule_date', models.DateField()),
            ],
        ),
    ]
